### ISSUE TITLE
Problem with clustal

### ISSUE THREAD

**Issue by basculethirascule** [SBRG/RiboRid_Design#7]
Hi

I've created the conda environment, downloaded the git file, installed muscle and installed ratelimit, then set up riborid.

When I come to run  ./design_oligos.py tests/test_data/Saureus_TCH1516.gb --ftype 'genbank'  I get the following error.

Invalid command line
Unknown option in

Traceback (most recent call last):
  File "./design_oligos.py", line 210, in <module>
    design_oligos(**params)
  File "./design_oligos.py", line 45, in design_oligos
    rrna_dict = {rt: RRNA(rrna_fa=split_names[rt], name=name,
  File "./design_oligos.py", line 45, in <dictcomp>
    rrna_dict = {rt: RRNA(rrna_fa=split_names[rt], name=name,
  File "/Users/platypus/RiboRid_Design-master/riborid/rRNA.py", line 36, in __init__
    self.consensus = self.get_consensus(clst=self.oname + '_clustal.clst',
  File "/Users/platypus/RiboRid_Design-master/riborid/rRNA.py", line 91, in get_consensus
    align = AlignIO.read(open(clst), "clustal")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/platypus/RiboRid_Design-master/riborid/rrd_res/rrd_16S_clustal.clst'

When I run ./design_oligos.py tests/test_data/Saureus_TCH1516_23S.fa --ftype 'fasta' I get the following.

Traceback (most recent call last):
  File "./design_oligos.py", line 210, in <module>
    design_oligos(**params)
  File "./design_oligos.py", line 43, in design_oligos
    split_names = split_rrna(rrna_fa, rrna_type, outdir)
  File "./design_oligos.py", line 117, in split_rrna
    raise ValueError(f'No {rt} rRNA found in {rrna_fa}')
ValueError: No 16S rRNA found in tests/test_data/Saureus_TCH1516_23S.fa

Any ideas what the issues are here and how to resolve them?

Thanks
Lesley

**Comment by sapoudel** [comment]
Hey Leslie,
I tried setting up a new environment and ran the command with genbank and it worked. How did you install muscle? It's possible that the script is not able to find muscle so its throwing the error. I installed with conda with the following command:

`conda install -c bioconda muscle`

As for the error with fasta file, by default it looks for 16S and 23S rRNA sequences. That file is used for internal testing and only contains 23S rRNA so it will throw an error. If you want to use it for testing you can modify the command to:

`./design_oligos.py tests/test_data/Saureus_TCH1516_23S.fa --ftype 'fasta' --rrna_type 23S`

Let me know if the conda installation solves your issue.
